### ISSUE TITLE
Node 20

### ISSUE THREAD

**Issue by andy-lawler-sbg** [Dylan700/sftp-upload-action#22]
Is this action potentially going to be updated to run on Node.js 20? With the deprecations coming up.

**Comment by Dylan700** [comment]
Yep! If you'd like to contribute, you are also welcome to submit a pull request for this.

**Comment by andy-lawler-sbg** [comment]
Question @Dylan700. I have the server running locally, how would I execute the action to test uploading some random file? Is there a way you have been doing it?

**Comment by Dylan700** [comment]
Hi @andy-lawler-sbg, thanks for letting me know. That's quite strange, the last 2 releases were a dependency update and limiting the concurrency due to an issue in the upstream library https://www.npmjs.com/package/ssh2-sftp-client

In regards to testing, the pull request you create should automatically test everything via the CI through the workflow file.

**Comment by andy-lawler-sbg** [comment]
Afternoon @Dylan700 v1.2.1 causes the issue for us, v1.2.2 also does not work so I'm going to assume the changes made in v1.2.1 are the ones causing the problem. Unsure why this would cause a problem for us if it's still working on your end as we aren't doing anything out of the ordinary. I've had to for now just fork and update v1.2.0 to Node20.

**Comment by Dylan700** [comment]
No worries @andy-lawler-sbg. I'll create a new release for Node 20 when I get the chance and let you know.

**Comment by Dylan700** [comment]
@andy-lawler-sbg this is now closed in #26. Special thanks to #24 also.

If you could try the new version and let me know how it goes that would be greatly appreciated. I can put you in the README.md as a thanks for all your help too.

**Comment by andy-lawler-sbg** [comment]
I'll try it out today @Dylan700 and let you know

**Comment by andy-lawler-sbg** [comment]
Just tested, still the same outcome as with v.1.2.1. The folder is created in the server but no files are transferred. Maybe it will work for others

**Comment by Dylan700** [comment]
Hmm, very strange. Maybe it's something with the server, although I don't see how that could be causing these issues... but no worries, thanks for helping out anways
